# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: dev
  jobs:
  - deployment: deployDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Hello World 1'

- stage: prod
  dependsOn: dev
  jobs:
  - deployment: deployProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
           - script: echo 'Hello World 2'

- stage: dr
  dependsOn: dev
  jobs:
  - deployment: 
    environment: dr
    strategy:
      runOnce:
        deploy:
          steps:
           - script: echo 'Hello World 3'