name: .NET

on:
    #push:
      #branches: [ "main" ]
    #pull_request:
      #branches: [ "main" ]
      
    workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Docker commands
      run: |
          docker login --username parteg132 --password ${{ DOCKER_PASS }}
          docker build . -t parteg132/booking-api-azure
          docker image push parteg132/booking-api-azure
      
    - name: Dotnet Publish
      run: dotnet publish .
