name: .NET

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
      
    workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Dotnet Publish
      uses: EasyDesk/action-dotnet-publish@v1.0.0
      with:
        path: . # optional, default is .
    # Directory where all packages will be put (default value is 'packages').
        output-dir: packages # optional, default is packages
    # Build configuration for the build (default value is 'Release').
        build-configuration: Release # optional, default is Release
    # Whether to skip the build using the --no-build flag (default value is 'true').
        skip-build: true # optional, default is true
